package codeqr;

import java.awt.Dimension;
import java.awt.image.BufferedImage;

/**
 * Création d'un Code QR
 *
 * @author Richard Lapointe (2020-30)
 */
public class frmPrincipale extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipale
     */
    public frmPrincipale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtTexteCodeQR = new javax.swing.JTextField();
        cmdCreerCodeQR = new javax.swing.JButton();
        jlblCodeQR = new javax.swing.JLabel();
        cmdQuitter = new javax.swing.JButton();
        cmdDemo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CodeQR");

        jtxtTexteCodeQR.setText("Texte pour encoder dans le code QR");

        cmdCreerCodeQR.setText("CodeQR");
        cmdCreerCodeQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreerCodeQRActionPerformed(evt);
            }
        });

        jlblCodeQR.setText("Le code QR va appraitre ici");

        cmdQuitter.setText("Quitter");
        cmdQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuitterActionPerformed(evt);
            }
        });

        cmdDemo.setText("Démo");
        cmdDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTexteCodeQR, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdCreerCodeQR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDemo)
                        .addGap(8, 8, 8)
                        .addComponent(cmdQuitter))
                    .addComponent(jlblCodeQR))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtTexteCodeQR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCreerCodeQR)
                    .addComponent(cmdQuitter)
                    .addComponent(cmdDemo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblCodeQR)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCreerCodeQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreerCodeQRActionPerformed
        try {
            final BufferedImage imgCodeQR = CodeBarre.getCodeQR( jtxtTexteCodeQR.getText(), 200 );
            jlblCodeQR.setText( "" );
            jlblCodeQR.setIcon( new javax.swing.ImageIcon( imgCodeQR ) );
            jlblCodeQR.setPreferredSize( new Dimension( imgCodeQR.getHeight(), imgCodeQR.getWidth() ) );
        } catch ( com.google.zxing.WriterException | java.awt.HeadlessException e ) {
            System.err.println( e );
        }
    }//GEN-LAST:event_cmdCreerCodeQRActionPerformed

    private void cmdQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuitterActionPerformed
        System.exit( 0 );
    }//GEN-LAST:event_cmdQuitterActionPerformed

    private void cmdDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDemoActionPerformed
        jtxtTexteCodeQR.setText( "https://mev-web.ca?f=p%2BPWgIxr1eR5qLeH1NxFrHrbjZJgvUbsUWXJr0Y8870vaYICA%2FKf%2BZ%2FCyDNsWFjefbHCtIazeFF9nb%2B6rj04XGc%2F4m9JtOvgUyyt5QMS4lXzqhpI2JP%2FMiah1OxqPZ91%2FwR%2F3ZJgJoT%2FgZh6VdsoqSd%2FuAYwF48XVaFFEV57V5BxortqdjD%2FGAOQrLBDeXsvoaOKxnPXKfsubLy%2FrnzTQ2R3k0gMBC5y9YvnqpGKujtXrAXFwt%2Fce9Tb0ovdQui%2BvaySnE4CeoB36YSsMzcog4x9PkMdzObp0K1wIwv%2BS7oMZQ09qDvEw2rSNKwshkMndPzMJLABxj%2Fy0r%2BDcuAO2WIMwlUgTsaTJID3iDcQHkJaGJ0EWD%2FbXE5WeTul%2Fi86aK41BfIwd%2BqLt388lAS%2BBVJaEOuamGZ5kvGV%2Fp1K5P8zsCzJuwwCa5GhXOew45FV82Jdsf0D4%2FGZvfJVcAe1crq4YEFRXqa63Dxmk1mqYMUekjHfRykBTH8XdnfUsN6r" );
        cmdCreerCodeQRActionPerformed( null );
    }//GEN-LAST:event_cmdDemoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Metal".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( frmPrincipale.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( () -> {
            new frmPrincipale().setVisible( true );
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCreerCodeQR;
    private javax.swing.JButton cmdDemo;
    private javax.swing.JButton cmdQuitter;
    private javax.swing.JLabel jlblCodeQR;
    private javax.swing.JTextField jtxtTexteCodeQR;
    // End of variables declaration//GEN-END:variables
}
